### ISSUE TITLE
Format command not following format provider model

### ISSUE THREAD

**Issue by kingscott00** [Leopotam/vscode-csharpfixformat#17]
The command palette command for formatting is currently "CSharp: Fix Format", but the model for registered format providers is for the command to be "Format Document" command.

Discussed this with vscode team in [VSCode issue 32497](https://github.com/Microsoft/vscode/issues/32497)

Reference: [VSCode formatting doc](https://code.visualstudio.com/docs/editor/codebasics#_formatting)

**Comment by Leopotam** [comment]
@kingscott00 this plugin cant follow to "Format Document" command, because it is usually used with another plugin - "C# omnisharp", that already registering some sort of formatting. Vscode not supports neither priority of multiple formatters for one file type, nor ability to force disable formatting registration for specified plugin after install. Its why this plugin use another command for custom formatting. You can set custom hotkey at hotkeys preferences, by default this plugin uses <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>I</kbd> combination.

**Comment by Leopotam** [comment]
@kingscott00 old issue - [VSCode issue 11609](https://github.com/Microsoft/vscode/issues/11609), still no final decision how to do it.

**Comment by Leopotam** [comment]
Behaviour can be changed only after solving this [omnisharp-vscode issue 1711](https://github.com/OmniSharp/omnisharp-vscode/issues/1711).

**Comment by Leopotam** [comment]
@kingscott00 #1735

**Comment by Leopotam** [comment]
@kingscott00 [omnisharp-vscode PR](https://github.com/OmniSharp/omnisharp-vscode/issues/1735).

**Comment by Leopotam** [comment]
@kingscott00 PR approved, i will start to work on following with standard formatting provider model after new version of omnisharp-vscode extension will be released (0.13.xx).

**Comment by Leopotam** [comment]
@kingscott00 implemented in 0.0.39 version as default FormatProvider (with default formatting, format on paste, format on save, etc). You can test it with code from develop branch of this repo and omnisharp plugin from their master branch (0.13 version still not released).

**Comment by Leopotam** [comment]
@kingscott00 0.0.39 released on official marketplace, you can uninstall custom package and install public release. thanks.
