### ISSUE TITLE
Feature Request: Newline formatting options

### ISSUE THREAD

**Issue by Siccity** [Leopotam/vscode-csharpfixformat#26]
By default, C# FixFormat places open braces on new lines 
like this:
```csharp
void Start()
{
    //...
}
```
A lot of users prefer having their open braces on the same line 
like this:
```csharp
void Start() {
    //...
}
```

**Comment by Leopotam** [comment]
> By default, C# FixFormat places open braces on new lines
Its not true, its how Omnisharp plugin works (default C# formatter). For using formatting feature of this plugin you should use special hotkey, described at readme page. You can even change this hotkey at your user settings.
Why not default hotkey? Because current version of Omnisharp force use it and ignore other plugins. I sent PR to omnisharp plugin one month ago, they approved it. When they will release new version - i will move to use default hotkey to format document without problems.
