### ISSUE TITLE
Thoughts on using omnisharp.json or some other configurable definition?

### ISSUE THREAD

**Issue by nexussays** [Leopotam/vscode-csharpfixformat#58]
Just wondering if you'd consider respecting `formattingOptions` in omnisharp.json in the working directory ahead of the VSCode settings. It would make it much easier to share settings across all devs on a project.

https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options

Defaults: https://github.com/OmniSharp/omnisharp-server/blob/master/OmniSharp/config.json

**Comment by Leopotam** [comment]
From readme:
> This extension helps to format C# code. When OmniSharp will support all features - will be deprecated.
> This extension not dependent on any 3dparty extensions (even omnisharp) and works as standalone formatting solution for current C#-file.

If you dependent only on `omnisharp` - better to wait when official omnisharp extension will provide proper formatting and use it instead of this extension.

Reasons, why I dont like idea of any external files (for ex. omnisharp.json):
* I cant control any adding / removing / updating settings at omnisharp.json.
* It can be not clear when I set some workspace / project formatting settings, but they will not work due to some special file was found somewhere in user profile folder or in project.
* Formatting options are not part of source code, visible omnisharp.json file at each repository by default - bad idea.
* Next request will be "full support of omnisharp formatting settings". Omnisharp has different settings / behaviour than this extension. It means - you cant use `vscode` on one machine and `rider` / `visual studio` on another machine without formatting issues. Better to use one IDE for all developers on one project.
* You already can share vscode settings in 2 ways:
    * per project, as `settings.json` file at `.vscode` folder inside project (like `jetbrains` apps does is with `.idea` folder).
    * per workspace - you can set same settings at all machines somehow (for example, through network share and symlink to vscode settings folder), then all projects will be formatted in same way.

**Comment by nexussays** [comment]
Thanks for your reply. I disagree with your reasoning but appreciate the explanation. Thanks for the extension!
