### ISSUE TITLE
Split code formatting off into its own csharp formatter for js beautify?

### ISSUE THREAD

**Issue by grofit** [Leopotam/vscode-csharpfixformat#77]
I have a scenario where I am looking to beautify generated c# code in a node process, and your library seems to do most of what I need, but all I need is the formatter bit for jsbeautify.

So would you be open to split the formatter into its own npm module that can be used with js beautify without needing vscode etc, then you can just reference that module from this project?

If its too much hassle for you no worries I can strip out the bits I need myself but I think this could be useful for others too.

**Comment by Leopotam** [comment]
Sorry for long delay, Im still on vacation. I have no planes to extract formatter as standalone npm module, because it means that I should provide support and fixes for all possible cases. I have no time for this, sorry. This extension was planned only as temporary replacement / features extending of official c# extension for vscode (omnisharp), nothing more. This extension will be deprecated when all features will be implemented at official extension.

**Comment by grofit** [comment]
ok thanks for the response
